[workspace]
resolver="2"

members = [
    "exercises/guessing_game",
    "projects/control_flow",
    "projects/functions",
    "projects/hello_cargo",
    "projects/hello_world",
    "projects/variables"
]
